openapi: 3.0.0
info:
  title: UNDP Project CRM API
  version: 1.0.0
servers:
  - url: https://b9db-2600-4041-5671-6000-e4ee-22c-abaa-8fe.ngrok-free.app/project?project_id=2023-AFG-045

paths:
  /project:
    get:
      summary: Get project details by project ID
      parameters:
        - in: query
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project to retrieve
      responses:
        '200':
          description: Project information successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  project_id:
                    type: string
                  project_number:
                    type: string
                  hq_co:
                    type: string
                  project_name:
                    type: string
        '404':
          description: Project not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

